### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by KevinZonda** [daodao97/gptpdf-ui#2]
Hi, I am query about the opensource license. It would be important for distribution. If possible, would you mind to add a `LICENSE` to the project (e.g., MIT etc.)? Thank you

**Comment by 190679163** [comment]
If possible, I'd like it to be under the Apache 2.0 license. LoL

**Comment by daodao97** [comment]
gptpdf and gptpdf-ui is licensed under the MIT License.

**Comment by KevinZonda** [comment]
Thank you!
